name: NPM Release

on:
  release:
    types: [released]

env:
  CI: true

jobs:
  publish:
    name: Build & Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install
        run: yarn install --immutable

      - name: Set version
        run: npm version --no-git-tag-version ${{github.event.release.tag_name}}

      - name: Build
        run: yarn build

      - name: npm pack
        run: cd dist && npm pack

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: "dist/create-polkadot-dapp-*.tgz"

      # v2.4.0
      # Working around "Action not found"
      # @see https://github.com/octokit/request-action/issues/315
      - uses: octokit/request-action@bbedc70b1981e610d89f1f8de88311a1fc02fb83
        with:
          route: POST /repos/paritytech/npm_publish_automation/actions/workflows/publish.yml/dispatches
          ref: main
          inputs: '${{ format(''{{ "repo": "{0}", "run_id": "{1}" }}'', github.repository, github.run_id) }}'
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION_TOKEN }}
